# Generated by Django 3.2.5 on 2021-07-29 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Especie',
                'verbose_name_plural': 'Especies',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_publi', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicación')),
                ('descripcion', models.TextField(help_text='Por favor sea lo mayormente descriptivo, hasta 1000 caracteres.', max_length=1000, verbose_name='Descripción')),
                ('contacto', models.CharField(help_text='Coloque las formas de contacto, por favor verifique.', max_length=200, verbose_name='Contacto')),
                ('disponibilidad', models.BooleanField(blank=True, default=True, verbose_name='Disponibilidad')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='Sin nombre aún :(', help_text='Si es que ya tiene nombre. Sino deje en blanco', max_length=20, null=True)),
                ('raza', models.CharField(blank=True, help_text='Si es de alguna raza conocida. Sino deje en blanco', max_length=20, null=True)),
                ('medida', models.CharField(default='otro', help_text='Que tamaño tiene?', max_length=20)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopcion.especie')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adopcion.post')),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
            },
        ),
    ]
