# Generated by Django 3.2.5 on 2021-08-19 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0006_alter_especie_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='especie',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='medida',
            field=models.CharField(choices=[('chico', 'Pequeño'), ('mediano', 'Mediano'), ('grande', 'Grande'), ('otro', 'No se')], default='otro', help_text='Seleccione el tamaño que cree mas adecuado.', max_length=15),
        ),
        migrations.AddField(
            model_name='post',
            name='nombre',
            field=models.CharField(blank=True, default='Sin nombre aún :(', help_text='Si es que ya tiene nombre. Sino deje en blanco', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='raza',
            field=models.CharField(blank=True, help_text='Solo escribe si conoces la raza. Sino deje en blanco', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='tipo',
            field=models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('otro', 'Otro')], default='otro', help_text='Seleccione la especie.', max_length=10),
        ),
        migrations.DeleteModel(
            name='Especie',
        ),
        migrations.DeleteModel(
            name='Mascota',
        ),
    ]
