# Generated by Django 3.2.5 on 2021-08-19 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0007_auto_20210818_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tipo',
            field=models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('otro', 'Otro')], help_text='Seleccione la especie.', max_length=10),
        ),
    ]
