# Generated by Django 3.2.5 on 2021-08-25 05:12

import adopcion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0008_alter_post_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to=adopcion.models.Post.user_directory_path),
        ),
    ]
