# Generated by Django 3.2.5 on 2021-08-25 05:21

import adopcion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0009_post_img1'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to=adopcion.models.Post.user_directory_path),
        ),
        migrations.AddField(
            model_name='post',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to=adopcion.models.Post.user_directory_path),
        ),
    ]
