# Generated by Django 3.2.5 on 2021-08-25 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0010_auto_20210825_0221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='img1',
            new_name='imgI',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='img2',
            new_name='imgII',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='img3',
            new_name='imgIII',
        ),
    ]
